home_page: overview/tutorial.md        # filepath under /source/_posts/
menu_page: menu/menu.md       # filepath under /source/_posts/
author_img:               # filepath of author image
favicon_url: mesh.svg  # filepath of favicon

zoom_image: true
codeblock:
  # Code Highlight theme
  # Available values: normal | night | night eighties | night blue | night bright | solarized | solarized dark | galactic
  highlight_theme: night
  copy_button:
    enable: true
    show_result: true

comments:
  utterances:
    enable: false
    user: # your github user name
    repo: # your github repo name
    theme: github-light # github-light | github-dark | github-dark-orange | icy-dark | dark-blue | photon-dark
  disqus:
    enable: false
    shortname: # your disqus shortname
  gitalk:
    enable: false
    githubID: # your github id
    repo: # GitHub repository e.g. kaiiiz.github.io
    ClientID: # GitHub Application Client ID
    ClientSecret: # GitHub Application Client Secret
    adminUser: # GitHub repository owner and collaborators
    labels: 'gitalk' # GitHub issue labels
    distractionFreeMode: true

google_analytics: # UA-XXXXX-Y

copyWords:
  copy_button: 'copy'
  copy_success: 'success'
  copy_failure: 'failed'

prevImg: prev.svg
nextImg: next.svg
